import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import toast from 'react-hot-toast'
import { ArrowRight, Check, Headphones, Inbox, LifeBuoy, MessageCircle, Plus, RefreshCw, Search, Send, ShieldCheck, Tag, UserRound, X } from 'lucide-react'
import { dateTime, number, request } from './api'

type TicketStatus='open'|'waiting_support'|'waiting_user'|'resolved'|'closed'
type TicketPriority='low'|'normal'|'high'|'urgent'
type TicketUser={id:string;displayName:string;mobile:string}
type TicketSummary={id:string;referenceCode:string;subject:string;category:string;priority:TicketPriority;status:TicketStatus;createdAtUtc:string;updatedAtUtc:string;lastReplyAtUtc:string;messageCount:number;lastMessage?:string;user?:TicketUser|null}
type TicketDetail=Omit<TicketSummary,'messageCount'|'lastMessage'>&{messages:Array<{id:string;isStaff:boolean;body:string;createdAtUtc:string}>}
type TicketList={items:TicketSummary[];counts:Record<string,number>}

const statusNames:Record<TicketStatus,string>={open:'جدید',waiting_support:'منتظر پشتیبانی',waiting_user:'پاسخ داده‌شده',resolved:'حل‌شده',closed:'بسته'}
const priorityNames:Record<TicketPriority,string>={low:'کم',normal:'عادی',high:'زیاد',urgent:'فوری'}
const categoryNames:Record<string,string>={technical:'فنی و API',billing:'مالی و پرداخت',account:'حساب کاربری',models:'مدل‌ها و سرویس‌ها',general:'سایر موارد'}
const statusTone=(status:TicketStatus)=>status==='resolved'?'mint':status==='closed'?'default':status==='waiting_support'?'danger':status==='waiting_user'?'violet':'blue'
const priorityTone=(priority:TicketPriority)=>priority==='urgent'?'danger':priority==='high'?'orange':'default'

export function TicketsPage({admin=false}:{admin?:boolean}){
  const [data,setData]=useState<TicketList>({items:[],counts:{}}),[selectedId,setSelectedId]=useState(''),[detail,setDetail]=useState<TicketDetail|null>(null)
  const [loading,setLoading]=useState(true),[detailLoading,setDetailLoading]=useState(false),[reply,setReply]=useState(''),[sending,setSending]=useState(false),[creating,setCreating]=useState(false)
  const [mobileConversationOpen,setMobileConversationOpen]=useState(false)
  const [search,setSearch]=useState(''),[status,setStatus]=useState(''),[priority,setPriority]=useState('')
  const base=admin?'/api/admin/tickets':'/api/tickets'
  const load=useCallback(async()=>{setLoading(true);try{const query=admin?`?search=${encodeURIComponent(search)}&status=${status}&priority=${priority}`:'';const result=await request<TicketList>(base+query);setData(result);setSelectedId(current=>current&&result.items.some(x=>x.id===current)?current:(result.items[0]?.id||''))}catch(e){toast.error((e as Error).message)}finally{setLoading(false)}},[admin,base,priority,search,status])
  const loadDetail=useCallback(async(id:string)=>{if(!id){setDetail(null);return}setDetailLoading(true);try{setDetail(await request<TicketDetail>(`${base}/${id}`))}catch(e){toast.error((e as Error).message)}finally{setDetailLoading(false)}},[base])
  useEffect(()=>{const timer=setTimeout(()=>{void load()},admin?250:0);return()=>clearTimeout(timer)},[admin,load])
  useEffect(()=>{void loadDetail(selectedId)},[loadDetail,selectedId])
  useEffect(()=>{if(!selectedId)setMobileConversationOpen(false)},[selectedId])
  useEffect(()=>{if(!mobileConversationOpen||!window.matchMedia('(max-width: 760px)').matches)return;requestAnimationFrame(()=>window.scrollTo({top:0,behavior:'auto'}))},[mobileConversationOpen])
  const filtered=useMemo(()=>admin?data.items:data.items.filter(x=>(!search||`${x.referenceCode} ${x.subject}`.toLowerCase().includes(search.toLowerCase()))&&(!status||x.status===status)),[admin,data.items,search,status])
  const send=async(e:FormEvent)=>{e.preventDefault();if(!detail||reply.trim().length<2)return;setSending(true);try{await request(`${base}/${detail.id}/messages`,{method:'POST',body:JSON.stringify({message:reply})});setReply('');toast.success(admin?'پاسخ برای کاربر ارسال شد':'پیام شما ارسال شد');await Promise.all([loadDetail(detail.id),load()])}catch(e){toast.error((e as Error).message)}finally{setSending(false)}}
  const update=async(changes:{status?:TicketStatus;priority?:TicketPriority})=>{if(!detail)return;try{await request(`${base}/${detail.id}`,{method:'PUT',body:JSON.stringify({status:changes.status||detail.status,priority:changes.priority||detail.priority})});toast.success('وضعیت تیکت به‌روزرسانی شد');await Promise.all([loadDetail(detail.id),load()])}catch(e){toast.error((e as Error).message)}}
  const closeTicket=async()=>{if(!detail)return;try{await request(`/api/tickets/${detail.id}/close`,{method:'POST'});toast.success('تیکت بسته شد');await Promise.all([loadDetail(detail.id),load()])}catch(e){toast.error((e as Error).message)}}
  const statusLabel=(value:TicketStatus)=>admin&&value==='waiting_user'?'منتظر پاسخ کاربر':statusNames[value]
  return <section className={`tickets-page${mobileConversationOpen?' conversation-open':''}`}>
    <div className="page-head"><div><span className="eyebrow-text">{admin?'مرکز عملیات پشتیبانی':'ارتباط با پشتیبانی'}</span><h1>{admin?'مرکز پشتیبانی کاربران':'پشتیبانی و تیکت‌ها'}</h1><p>{admin?'تیکت‌ها را اولویت‌بندی کنید، پاسخ دهید و تا حل کامل پیگیری کنید.':'سؤال یا مشکل خود را مطرح کنید؛ تیم پشتیبانی پاسخ را همین‌جا ثبت می‌کند.'}</p></div><div className="head-actions"><button className="ghost-btn" onClick={()=>void load()}><RefreshCw/>به‌روزرسانی</button>{!admin&&<button className="primary-btn" onClick={()=>setCreating(true)}><Plus/>تیکت جدید</button>}</div></div>
    <div className="ticket-kpis"><div><Inbox/><span><b>{number((data.counts.open||0)+(data.counts.waiting_support||0)+(data.counts.waiting_user||0))}</b><small>در حال پیگیری</small></span></div><div><MessageCircle/><span><b>{number(data.counts.waiting_support||0)}</b><small>منتظر پشتیبانی</small></span></div><div><Check/><span><b>{number((data.counts.resolved||0)+(data.counts.closed||0))}</b><small>حل‌شده و بسته</small></span></div></div>
    <div className="ticket-toolbar"><div className="search-box"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={admin?'شماره تیکت، موضوع، نام یا موبایل...':'جست‌وجوی تیکت...'}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">همه وضعیت‌ها</option><option value="open">جدید</option><option value="waiting_support">منتظر پشتیبانی</option><option value="waiting_user">{admin?'منتظر پاسخ کاربر':'پاسخ داده‌شده'}</option><option value="resolved">حل‌شده</option><option value="closed">بسته</option></select>{admin&&<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">همه اولویت‌ها</option><option value="urgent">فوری</option><option value="high">زیاد</option><option value="normal">عادی</option><option value="low">کم</option></select>}</div>
    <section className={`ticket-workspace${mobileConversationOpen?' conversation-open':''}`}>
      <aside className="ticket-list">{loading?<div className="ticket-loading"><RefreshCw className="spin"/>در حال دریافت تیکت‌ها...</div>:filtered.length?filtered.map(item=><button key={item.id} className={selectedId===item.id?'active':''} onClick={()=>{setSelectedId(item.id);setMobileConversationOpen(true)}}><div className="ticket-list-top"><code dir="ltr">{item.referenceCode}</code><TicketBadge tone={statusTone(item.status)}>{statusLabel(item.status)}</TicketBadge></div><strong>{item.subject}</strong>{admin&&item.user&&<span className="ticket-user"><UserRound/>{item.user.displayName}<small dir="ltr">{item.user.mobile}</small></span>}<p>{item.lastMessage||'بدون پیام'}</p><footer><span><MessageCircle/>{number(item.messageCount)}</span><span><Tag/>{categoryNames[item.category]}</span><time>{dateTime(item.updatedAtUtc)}</time></footer></button>):<div className="ticket-empty"><LifeBuoy/><b>تیکتی وجود ندارد</b><p>{admin?'صف پشتیبانی در حال حاضر خالی است.':'برای ارتباط با پشتیبانی، اولین تیکت خود را بسازید.'}</p>{!admin&&<button className="primary-btn compact" onClick={()=>setCreating(true)}><Plus/>ساخت تیکت</button>}</div>}</aside>
      <div className="ticket-conversation">{detailLoading?<div className="ticket-loading"><RefreshCw className="spin"/>در حال بازکردن گفتگو...</div>:detail?<><header className="ticket-conversation-head"><button type="button" className="ticket-mobile-back" aria-label="بازگشت به فهرست تیکت‌ها" onClick={()=>setMobileConversationOpen(false)}><ArrowRight aria-hidden="true"/><span>فهرست تیکت‌ها</span></button><div><div><code dir="ltr">{detail.referenceCode}</code><TicketBadge tone={statusTone(detail.status)}>{statusLabel(detail.status)}</TicketBadge><TicketBadge tone={priorityTone(detail.priority)}>اولویت {priorityNames[detail.priority]}</TicketBadge></div><h2>{detail.subject}</h2><span>{categoryNames[detail.category]} · ایجاد در {dateTime(detail.createdAtUtc)}</span></div>{!admin&&detail.status!=='closed'&&<button className="ghost-btn compact" onClick={closeTicket}><X/>بستن تیکت</button>}</header>{admin&&<div className="ticket-admin-controls"><div><label>وضعیت</label><select value={detail.status} onChange={e=>void update({status:e.target.value as TicketStatus})}><option value="open">جدید</option><option value="waiting_support">منتظر پشتیبانی</option><option value="waiting_user">منتظر پاسخ کاربر</option><option value="resolved">حل‌شده</option><option value="closed">بسته</option></select></div><div><label>اولویت</label><select value={detail.priority} onChange={e=>void update({priority:e.target.value as TicketPriority})}><option value="urgent">فوری</option><option value="high">زیاد</option><option value="normal">عادی</option><option value="low">کم</option></select></div>{detail.user&&<div className="ticket-customer"><UserRound/><span><b>{detail.user.displayName}</b><small dir="ltr">{detail.user.mobile}</small></span></div>}</div>}<div className="ticket-messages">{detail.messages.map(message=><article key={message.id} className={message.isStaff?'staff':'customer'}><div className="message-avatar">{message.isStaff?<Headphones/>:<UserRound/>}</div><div><header><b>{message.isStaff?'پشتیبانی AiBus':admin?(detail.user?.displayName||'کاربر'):'شما'}</b><time>{dateTime(message.createdAtUtc)}</time></header><p>{message.body}</p></div></article>)}</div>{detail.status==='closed'&&!admin?<div className="ticket-closed"><ShieldCheck/><span><b>این تیکت بسته شده است</b><small>برای موضوع جدید، تیکت دیگری بسازید.</small></span></div>:<form className="ticket-composer" onSubmit={send}><textarea rows={3} value={reply} onChange={e=>setReply(e.target.value)} placeholder={admin?'پاسخ دقیق و راهنمایی لازم را برای کاربر بنویسید...':'پیام خود را برای تیم پشتیبانی بنویسید...'}/><div><small>حداکثر ۵۰۰۰ کاراکتر</small><button className="primary-btn" disabled={sending||reply.trim().length<2}>{sending?<RefreshCw className="spin"/>:<Send/>}{admin?'ارسال پاسخ':'ارسال پیام'}</button></div></form>}</>:<div className="ticket-empty conversation"><MessageCircle/><b>یک تیکت را انتخاب کنید</b><p>تاریخچه گفتگو و امکان پاسخ‌گویی اینجا نمایش داده می‌شود.</p></div>}</div>
    </section>
    {creating&&<NewTicket close={()=>setCreating(false)} done={ticket=>{setCreating(false);setSelectedId(ticket.id);setMobileConversationOpen(true);void load()}}/>}
  </section>
}

function TicketBadge({children,tone}:{children:ReactNode;tone:string}){return <span className={`ticket-badge ${tone}`}>{children}</span>}

function NewTicket({close,done}:{close:()=>void;done:(ticket:TicketDetail)=>void}){
  const [form,setForm]=useState({subject:'',category:'technical',priority:'normal',message:''}),[busy,setBusy]=useState(false)
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{const ticket=await request<TicketDetail>('/api/tickets',{method:'POST',body:JSON.stringify(form)});toast.success('تیکت شما ثبت شد');done(ticket)}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
  return <div className="modal-layer" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal ticket-create"><header><div><h3>ساخت تیکت جدید</h3><p>اطلاعات دقیق‌تر، پاسخ‌گویی سریع‌تر را ممکن می‌کند.</p></div><button className="icon-btn" onClick={close}><X/></button></header><div className="modal-body"><form onSubmit={submit}><div className="form-grid"><label className="field span-2"><span>موضوع تیکت</span><input required minLength={3} maxLength={160} value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="خلاصه‌ای روشن از سؤال یا مشکل"/></label><label className="field"><span>دسته‌بندی</span><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="technical">فنی و API</option><option value="billing">مالی و پرداخت</option><option value="account">حساب کاربری</option><option value="models">مدل‌ها و سرویس‌ها</option><option value="general">سایر موارد</option></select></label><label className="field"><span>اولویت</span><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="low">کم</option><option value="normal">عادی</option><option value="high">زیاد</option><option value="urgent">فوری</option></select></label><label className="field span-2"><span>شرح کامل</span><textarea required minLength={2} maxLength={5000} rows={7} value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="جزئیات، متن خطا و اقداماتی که انجام داده‌اید را بنویسید..."/><small>{number(form.message.length)} از ۵۰۰۰ کاراکتر</small></label></div><div className="ticket-create-note"><ShieldCheck/><span><b>گفتگوی امن با پشتیبانی</b><small>این تیکت فقط برای شما و مدیران پشتیبانی قابل مشاهده است.</small></span></div><div className="modal-actions"><button type="button" className="ghost-btn" onClick={close}>انصراف</button><button className="primary-btn" disabled={busy}>{busy?<RefreshCw className="spin"/>:<Send/>}ثبت و ارسال تیکت</button></div></form></div></div></div>
}
