<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ArkaCode</AssemblyName>
    <RootNamespace>ArkaCode</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.0.0</Version>
  </PropertyGroup>
</Project>
